[package]
name = "datafusion-federation"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true

[lib]
name = "datafusion_federation"
path = "src/lib.rs"

[dependencies]
async-trait.workspace = true
datafusion.workspace = true
